# 项目相关配置
ruoyi:
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
#  profile: D:/ruoyi/uploadPath
#  profile: /home/hronesh-abp/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /client
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  mail:
    sendFrom: " <info@hrone.io>"
    host: smtp.office365.com
    port: 587
    username: info@hrone.io
    password: HROne@699
    default-encoding: UTF-8
    properties:
      mail:
        debug: false
        smtp:
          ssl:
            trust: smtp.office365.com
          auth: true # 需要验证登录名和密码
          starttls:
            enable: true
            required: true
  freemarker:
    # 模板后缀名
    suffix: .ftl
    # 文档类型
    content-type: text/html
    # 页面编码
    charset: UTF-8
    # 页面缓存
    cache: false
    # 模板路径
    template-loader-path: classpath:/templates/
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 50MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.nnroad.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/**.xml
  global-config:
    db-config:
      # 主键默认自增
      id-type: AUTO
    enable-sql-runner: true
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

sys:
  # 外网访问路径
  #  accessPath: https://app.hrone.com/
  accessPath: https://hrone.jljhr.com/
  # 定时任务模式(0启用1关闭)
  quartzMode: 0
  # 外网访问路径
#  accessPath: app.hrone.com

# Azure File Shares Cloud
azure:
  requestLifeTime: 2 #min
  fileShare:
    accountName: devhronestorage
    shareName: devhronefs
    sasToken: ?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2025-07-10T15:52:14Z&st=2023-07-10T07:52:14Z&spr=https&sig=9ihvPGnoo4KJGa7iA12Qa2PioCSF%2BCinYS2VJuZu%2B0w%3D

dataSecurity:
  secretKey: fWjK5ES5hmHhvBdgdauqSIR4ts0nDPuV


